// to use the 'expect' function we need to bring in the Chai library...
const { expect } = require('chai');
const { ethers } = require('hardhat');
// the above line pulls the ethers library from the hardhat library...
describe('Token', () => {
	// Tests go inside here...
	it('has a name', async () => {
		// Fetch Token from Blockchain with Ethers.js (2 step)...
		// This imports/gets the contract itself but...
		const Token = await ethers.getContractFactory('Token')
		// To get a "deployed instance of that contract" we need this...
		let token = await Token.deploy()
		// Read token name...
		const name = await token.name()
		// Check that name is correct...
		expect(name).to.equal('My Token')
	})
})
